CREATE TABLE SHIPWRECK(
	ID INT AUTO_INCREMENT,
	DESCRIPTION VARCHAR(255),
	NAME VARCHAR(255),
	CONDITION VARCHAR(255),
	LATITUDE DOUBLE,
	LONGITUDE DOUBLE,
	DEPTH INT,
	YEAR_DISCOVERED INT
);

CREATE TABLE QUERY(
	ID INT AUTO_INCREMENT,
	USER_ID INT,
	DESCRIPTION VARCHAR(255),
	KEYWORD VARCHAR(255),
	HASHTAG VARCHAR(255),
	TWEET_OWNER VARCHAR(255),
	RESULT_TYPE VARCHAR(255),
	LANGUAGE VARCHAR(255),
	LATITUDE DOUBLE,
	LONGITUDE DOUBLE
);

CREATE TABLE TWEET(
	ID INT AUTO_INCREMENT,
	USER_ID INT,
	CONTENT VARCHAR(255),
	KEYWORD VARCHAR(255),
	HASHTAG VARCHAR(255),
	TWEET_OWNER VARCHAR(255),
	RESULT_TYPE VARCHAR(255),
	LANGUAGE VARCHAR(255),
	LATITUDE DOUBLE,
	LONGITUDE DOUBLE
);

CREATE TABLE USER(
	ID INT AUTO_INCREMENT,
	STATUS VARCHAR(3),
	NAME VARCHAR(255),
	MAIL VARCHAR(255),
	PASSWORD VARCHAR(255),
	TWITTER_ACCOUNT VARCHAR(255),
	AVATAR VARCHAR(255)
);
